added set.hpp
VolodyaSoldatenkov/set-review pull request #1
Opened 2019-06-14 17:47 UTC by VolodyaSoldatenkov

2019-06-23 08:47 UTC, Skird requested changes
Вроде почти все норм. Некоторые моменты отметил

2019-06-23 08:47 UTC, Skird commented on set.hpp
> +        static Color c;
А зачем эта статическая переменная? Чем этот код отличается от `return n ? n->color : black`?

2019-06-23 08:47 UTC, Skird commented on set.hpp
> +        *cur = new Node{std::move(value), nullptr, nullptr, prev, red};
Опасность.
Увы, new всегда может бросить исключение и с этим ничего не поделать.
В целом, не ловить его - это нормально, но поскольку эта штука вызывается в конструкторе возможны красивые сценарии утечки: пользователь делает структуру по двум итераторам, у него кончается память в процессе. Бросается exception, который он ловит, понимает, что памяти-то много, что-то там чистит и работает дальше. Но есть один нюанс: из конструктора было брошено исключение, поэтому деструктор вызван не будет (объект не сконструировался). Память утекла, потому что в рекурсии было много успешных вызовов new.
Можно поиграть локально запуская процесс, после команды ulimit -Sv 100000 (ML 100 Mb, правда не работает в сочетании с valgrind и asan по понятным причинам)

2019-06-23 08:47 UTC, Skird commented on set.hpp
> +        Node* res = new Node{v->value, nullptr, nullptr, p, v->color};
Тут тоже надо аккуратно с new

2019-06-23 13:26 UTC, VolodyaSoldatenkov commented on set.hpp
> +        static Color c;
Чтобы можно было писать непонятный код в стиле `color(v) = black`, не думая о том, что `v` может и не существовать.

2019-06-23 13:30 UTC, VolodyaSoldatenkov commented on set.hpp
> +        Node* res = new Node{v->value, nullptr, nullptr, p, v->color};
Здесь всё просчитано: создаётся вершина, если случился фейл — исключение перехватывает родитель, чистит поддеревья (если вдруг уже появилось левое, к примеру) и выбрасывает исключение дальше.

2019-06-23 13:35 UTC, VolodyaSoldatenkov commented on set.hpp
> +        *cur = new Node{std::move(value), nullptr, nullptr, prev, red};
`insert()` безопасен — все изменения структуры дерева происходят уже после создания новой вершины. Из конструктора, принимающего итераторы, память действительно могла утечь, поправил это в https://github.com/VolodyaSoldatenkov/set-review/pull/1/commits/78372f929da5391f37f3f62cef9b197fbef80fec.

2019-06-26 10:16 UTC, Skird commented on set.hpp
> +        static Color c;
Неочевидная хрень, ну ладно, что ж

2019-06-26 10:17 UTC, merged